blank_issues_enabled: false
contact_links:
  - name: "ğŸš€ FormPD - MCTI"
    url: https://formpd.mcti.gov.br/empresas/representante
    about: Preenchimento de formulÃ¡rios de PD&I pelas empresas.
  
  - name: "ğŸ” FormAnÃ¡lise - MCTI"
    url: https://mcti.gov.br/
    about: AnÃ¡lise tÃ©cnica de formulÃ¡rios e emissÃ£o de pareceres.

  - name: "ğŸ“‚ Pasta da Rede COIAI"
    url: "file://P:/COIAI/GestÃ£o de Dados"
    about: Acesso direto a documentos de gestÃ£o e histÃ³rico na rede.

  - name: "ğŸ›ï¸ Portal MCTI"
    url: https://www.gov.br/mcti
    about: Site oficial do MinistÃ©rio da CiÃªncia, Tecnologia e InovaÃ§Ã£o.