blank_issues_enabled: false
contact_links:
  - name: Pasta da Rede da COIAI 
#   url: P:/COIAI/Gestão de Dados
    about: Para informações oficiais do Departamento de Estatística da Universidade de Brasília. 